= Adaptive Storage Framework

Adaptive Storage Framework is primarily a framework revolving around storage rendering, providing options to change graphics depending on contents, tweak how items get displayed, how many graphics get displayed, how they get colored, how to display text. Its mod extension offers a couple other features like more fine grained storage capacity control and temperature controls. The framework also always adds a contents tab, a group tab for buildings in a storage group and enhances selection behaviour for storage buildings.

== Getting started
Included in the framework are two abstract ThingDefs in https://github.com/bbradson/Adaptive-Storage-Framework/blob/main/Defs/ThingDefBase.xml[Defs/ThingDefBase.xml], "AdaptiveStorageBase" and "AdaptiveStorageMinifiableBase". Declaring a storage building usually starts with setting one of those as parent by using the `ParentName` attribute. `Minifiable` differs by making the building minifiable.

Alternatively, it's technically enough to set the `<thingClass>` to `AdaptiveStorage.ThingClass`. Consider looking into the defs to see what fields get set by default in there though.

For now, the wiki is still being written. Most data is available in the https://github.com/bbradson/Adaptive-Storage-Framework/blob/main/info.txt[info.txt] file.
GraphicsDefs are declared for all things rendering, with the ThingDef attachment made through its targetDef field. The Extension for other functions is added to the modExtensions field of ThingDefs it's meant for.

Having god mode active in-game causes additional buttons for dev functions to show up on selected storage buildings.